test stable and unstable thymis input

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -71,6 +71,7 @@ jobs:
         with:
           attic_token: ${{ secrets.ATTIC_TOKEN }}
           script: |
+            export THYMIS_FLAKE_ROOT='..'
             npm run test 2>&1 | tee output.log
             if grep -q -e "Error: A snapshot doesn't exist at" -e "Screenshot comparison failed" output.log; then
               echo "Playwright tests failed due to a snapshot issue"
@@ -98,6 +99,65 @@ jobs:
             **To approve the snapshot changes and update the snapshots, please comment:** /approve-snapshots
           comment-tag: playwright-snapshots
           mode: recreate
+
+  test-frontend-integration-stable-input:
+    runs-on: ubuntu-22.04-arm
+    steps:
+      - uses: actions/checkout@v4
+      - uses: ./.github/actions/setup-nix
+        with:
+          attic_token: ${{ secrets.ATTIC_TOKEN }}
+      - name: Install Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: "20"
+      - name: Install dependencies
+        run: |
+          npm ci
+        working-directory: frontend
+      - name: Build application
+        uses: ./.github/actions/run-command-with-nix-cache-upload
+        with:
+          attic_token: ${{ secrets.ATTIC_TOKEN }}
+          script: |
+            nix build .#thymis-controller --print-build-logs
+      - name: Install Playwright Browser
+        run: |
+          npx playwright install --with-deps
+        working-directory: frontend
+      - name: Run tests
+        uses: ./.github/actions/run-command-with-nix-cache-upload
+        with:
+          attic_token: ${{ secrets.ATTIC_TOKEN }}
+          script: |
+            npm run test 2>&1 | tee output.log
+            if grep -q -e "Error: A snapshot doesn't exist at" -e "Screenshot comparison failed" output.log; then
+              echo "Playwright tests failed due to a snapshot issue"
+              echo "SNAPSHOT_DIFFERENCES=true" >> $GITHUB_ENV
+            fi
+            if grep -q -E -e "[[:digit:]]+ failed" -e "was not able to start" output.log; then
+              echo "Playwright tests failed"
+              exit 1
+            fi
+          working-directory: frontend
+      - uses: actions/upload-artifact@v4
+        id: artifact-upload
+        if: always()
+        with:
+          name: playwright-report
+          path: frontend/playwright-report/
+          retention-days: 30
+      - name: Comment on PR with report link
+        uses: thollander/actions-comment-pull-request@v3
+        if: ${{ always() && github.event_name == 'pull_request' && env.SNAPSHOT_DIFFERENCES == 'true' }}
+        with:
+          message: |
+            ### Playwright visual snapshot differences were detected.
+            View the [Playwright report](${{ steps.artifact-upload.outputs.artifact-url }}) to review the visual differences.
+            **To approve the snapshot changes and update the snapshots, please comment:** /approve-snapshots
+          comment-tag: playwright-snapshots
+          mode: recreate
+
   test-pre-commit:
     if: ${{ github.event_name != 'pull_request_target' }}
     runs-on: ubuntu-latest
