test with empty path

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -90,7 +90,14 @@ jobs:
           script: |
             set +e  # revert the default `set -e`
             export THYMIS_FLAKE_ROOT='..'
-            nix develop .#onlyPlaywrightBrowsers --command npm run test 2>&1 | tee output.log
+            cd frontend
+            OUR_NIX=$(readlink -f $(which nix))
+            OUR_NIX_PARENT=$(dirname $OUR_NIX)
+            TEE=$(which tee)
+            OLD_PATH=$PATH
+            export PATH=$OUR_NIX_PARENT
+            $OUR_NIX develop .#forNpmTesting --command npm run test 2>&1 | $TEE output.log
+            export PATH=$OLD_PATH
             PLAYWRIGHT_EXIT_CODE=$?
             if grep -q -e "Error: A snapshot doesn't exist at" -e "Screenshot comparison failed" output.log; then
               echo "Playwright tests failed due to a snapshot issue"
@@ -200,15 +207,30 @@ jobs:
           attic_token: ${{ secrets.ATTIC_TOKEN }}
           github_token: ${{ secrets.GITHUB_TOKEN }}
           script: |
-            nix develop .#onlyPlaywrightBrowsers --command npm run test 2>&1 | tee output.log
+            set +e  # revert the default `set -e`
+            # export THYMIS_FLAKE_ROOT='..' # stable input needs THYMIS_FLAKE_ROOT to be unset
+            cd frontend
+            OUR_NIX=$(readlink -f $(which nix))
+            OUR_NIX_PARENT=$(dirname $OUR_NIX)
+            TEE=$(which tee)
+            OLD_PATH=$PATH
+            export PATH=$OUR_NIX_PARENT
+            $OUR_NIX develop .#forNpmTesting --command npm run test 2>&1 | $TEE output.log
+            export PATH=$OLD_PATH
+            PLAYWRIGHT_EXIT_CODE=$?
             if grep -q -e "Error: A snapshot doesn't exist at" -e "Screenshot comparison failed" output.log; then
               echo "Playwright tests failed due to a snapshot issue"
               echo "SNAPSHOT_DIFFERENCES=true" >> $GITHUB_ENV
+            fi
+            if grep -q -E -e "npx playwright install" -e "error: attribute '\"[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+\"' missing" output.log; then
+              echo "Playwright tests failed due to missing browsers"
+              echo "MISSING_BROWSERS=true" >> $GITHUB_ENV
             fi
             if grep -q -E -e "[[:digit:]]+ failed" -e "was not able to start" output.log; then
               echo "Playwright tests failed"
               exit 1
             fi
+            exit $PLAYWRIGHT_EXIT_CODE
           working-directory: frontend
       - uses: actions/upload-artifact@v4
         id: artifact-upload
